# Ported from vcm (ssm-report tooling) 2026-0119-tc2/py/vcm/v2/latex.py — Phase 1 engine/library tier.
# the LaTeX assembler engine. See py/ae/report/MIGRATION.md.
import sys
import datetime
import itertools
import lzma
import collections
import json
import re
# import pprint
from pathlib import Path

# import ae.utils.datetime
from ae.utils.time_series import TimeSeriesRange
from .dirs import lab_title, lab_of_dir

# ======================================================================

sPackages = r"""
\usepackage[cm]{fullpage}
\usepackage{verbatim}
\usepackage[table]{xcolor}
\usepackage{tikz}               % draw filled circles in \ColorCodedByRegion

\usepackage{graphicx}           % multiple pdfs per page, pdf
\usepackage[export]{adjustbox}  % frame in \includegraphics
\usepackage{grffile}            % to allow .a.pdf in \includegraphics
\usepackage{pdfpages}           % phylogenetic tree
\usepackage{fancyhdr}           % keep page numbers in embedded phylogenetic tree
\usepackage{calc}
\usepackage{hyperref}           % ToC entries as links
\usepackage{tocloft}            % \cftsetindents
\usepackage[toc,page]{appendix} % Appendice
\usepackage{titletoc}           % ToC entries without numbers
\usepackage[T1]{fontenc}        % fonts
\usepackage{times}              % font
\usepackage{geometry}           % newgeometry
"""

def head(documentclass: str, append: list[str] = []) -> list[str]:
    return [
        "% !TEX encoding = UTF-8 Unicode",
        f"% generated by {sys.argv[0]} on {_now()}",
        documentclass,
        r"\pagestyle{empty}",
        sPackages,
    ] + append

# ======================================================================

def report_commands() -> list[str]:
    return [
        *_blank_page(),
        *_remove_section_numbering(),
        *_table_of_contents(),
        # latex.T_AntigenicMapTable,
        *_whocc_statistics_table(),
        *_cbox(),
        *_color_coded_by_region(),
        *_geographic_map_table(),
        *_antigenic_map_table(),
        *_whole_page_pdf(),
    ]

def begin_document() -> list[str]:
    return [
        r"\begin{document}",
        r"\rmfamily",
    ]

def end_document() -> list[str]:
    return [
        r"\end{document}"
    ]

def newgeometry(top: str = "3em", bottom: str = "5em", left: str = "2.5em", right: str = "2.5em") -> list[str]:
    return [
        fr"\newgeometry{{top={top}, bottom={bottom}, left={left}, right={right}}}",
    ]

def page_numbering(make: bool) -> list[str]:
    if make:
        return []
    else:
        return [
            r"\pagenumbering{gobble}"
        ]

def time_stamp(make: bool) -> list[str]:
    if make:
        return [fr"\par\vspace*{{\fill}}\tiny{{Report generated: {_now()}}}  \newpage"]
    else:
        return []

# ----------------------------------------------------------------------

def cover(hemisphere: str, year: str, teleconference: str | None, meeting_date: str, cover_space: dict[str, str], addendum: str | None = None) -> list[str]:
    """cover_space: {"top": "", "after_meeting_date": ""} """
    main_title = fr"Information for the WHO Consultation\\ on the Composition of Influenza Vaccines\\ for the {hemisphere} Hemisphere {year}"
    return [
        r"\thispagestyle{empty}{",
        r"\quotation",
        fr"\vspace*{{{cover_space['top']}}}",
        r"{\fontsize{22}{26} \selectfont \noindent \textbf{" + main_title + r"} \par }",
        r"\vspace{90pt}{ \fontsize{19}{24} \selectfont \noindent",
        teleconference or "",
        r"\vspace{10pt} \noindent",
        addendum or "",
        r"\vspace{50pt} \noindent",
        meeting_date,
        r"\par}",
        fr"\vspace{{{cover_space['after_meeting_date']}}}{{\large \noindent",
        "Center for Pathogen Evolution\n",
        # "WHO Collaborating Center for Modeling, Evolution, and Control of Emerging Infectious Diseases\n",
        r"\vspace{10pt} \noindent",
        r"University of Cambridge, United Kingdom",
        "\n",                   # do NOT remove two empty lines!
        r"} }",
    ]

def toc() -> list[str]:
    return [r"\newpage \tableofcontents"]

def section_title(text: str) -> list[str]:
    return [fr"\newpage \section{{{text}}}"]

def geographic(subtype: str, title: str, coloring: list[dict[str, object]], time_series: TimeSeriesRange, desc: str) -> list[str]:
    images = [Path("geo", f"{subtype}-{mstart.strftime('%Y-%m')}.pdf").resolve() for mstart in time_series.range_begin()]
    images_per_page = 3
    groups = "\n\\newpage\n".join(r"\begin{GeographicMapsTable} " + " ".join(f"\\GeographicMap{{{img}}} \\\\\n" for img in images[i:i+images_per_page]) + r"\end{GeographicMapsTable}" for i in range(0, len(images), images_per_page))
    return [
        fr"\subsection{{{title} geographic data}}",
        r"\vspace*{3em}",
        f"Month-by-month geographic time series from {time_series.front().strftime('%B %Y')} to {time_series.back().strftime('%B %Y')}",
        r"\vspace*{1em}",
        r"\noindent",
        *_prepare_geographic_coloring(coloring),
        r"\vspace*{1em}",
        desc,
        r"\newpage",
        groups
    ]

def time_series(subtype: str, title: str, dirs: list[Path], time_series: TimeSeriesRange, current_stat: Path, previous_stat: Path | None = None, chart_no: int = 1) -> list[str]:
    return list(itertools.chain.from_iterable([
        r"\newpage" if dir_no else "",
        fr"\subsection{{{lab_title(lab_of_dir(dir))} {title} antigenic data}}",
        r"\vspace*{3em}",
        fr"\noindent Month-by-month time series from {time_series.front().strftime('%B %Y')} to {time_series.back().strftime('%B %Y')}",
        r"\vspace*{1em}",
        r"\noindent Grid indicates 1 unit of antigenic distance, a 2-fold dilution in HI titer.",
        r"\vspace*{1em}",
        r"\noindent Reference antigens and antisera no fill. Epi strains (small dots) colored by region:",
        r"\ColorCodedByRegion",
        r"\vspace*{3em}",
        *_statistics_table(subtype=subtype, lab=lab_of_dir(dir), time_series=time_series, current_stat=current_stat, previous_stat=previous_stat),
        *_maps_in_columns(images=[Path(dir, f"out.{chart_no}.ts-{date}.pdf") for date in time_series.range_begin_str()], columns=2, newpage=True),
    ] for dir_no, dir in enumerate(dirs)))

def phylogenetic_tree(subtype: str, title: str, trees: list[Path]) -> list[str]:
    return [
        r"\newpage",
        fr"\subsection{{{title} phylogenetic tree}}",
        r"\vspace*{3em}",
        *_phylogenetic_tree_description(),
        *([r"\vspace*{1em}"] + _phylogenetic_tree_2_description() if len(trees) > 1 else []),
        *whole_page_image(trees),
    ]

def maps_in_columns(images: list[Path], columns: int, title: str, top_text: str | None = None, bottom_text: str | None = None, bottom_text_vspace: str = "3em", bottom_text_font_size: list[float] = [7.0, 7.0]) -> list[str]:
    return [
        r"\newpage",
        fr"\subsection{{{title}}}" if title else "",
        r"\noindent " + top_text if top_text else "",
        *_maps_in_columns(images=images, columns=columns, newpage=False),
        *([rf"\vspace*{{{bottom_text_vspace}}}", rf"\noindent {{\fontsize{{{bottom_text_font_size[0]}}}{{{bottom_text_font_size[1]}}} \selectfont \textbf{{{bottom_text}}} }}"] if bottom_text else []),
    ]

def _maps_in_columns(images: list[Path], columns: int, newpage: bool) -> list[str]:

    setup: list[dict[str, str | int]] = [
        {},                     # columns: 0
        {},                     # columns: 1
        {                       # columns: 2
            "images_per_page": 6,
            "tex_begin": r"\begin{AntigenicMapTableWithSep}{7.0pt}{3.5}{9 / 30}",  # sep=7.5 arraystretch=3.5 scale=9/30
            "tex_end": r"\end{AntigenicMapTableWithSep}",
        },
        {                       # columns: 3
            "images_per_page": 6,
            "tex_begin": r"\begin{AntigenicMapTable3WithSep}{7.0pt}{3.5}{14 / 30}",
            "tex_end": r"\end{AntigenicMapTable3WithSep}",
        },
    ]

    def make_map(img: Path | None) -> str:
        if img:
            if img.exists():
                return fr"\AntigenicMap{{{img.resolve()}}}"
            else:
                return fr"{{\fontsize{{12}}{{16}} \selectfont \noindent \rotatebox{{45}}{{ \textbf{{ \textcolor{{red}}{{{img}}} }} }}}}"
        else:
            return fr"\hspace{{18em}} {{\fontsize{{12}}{{16}} \selectfont \noindent \rotatebox{{45}}{{ \textbf{{ \textcolor{{red}}{{ }} }} }}}}"

    def n_maps(imgs: list[Path | None]) -> str:
        return " & ".join(make_map(img) for img in imgs) + r"\\"

    result = []
    for page_no, images_on_page in enumerate(itertools.zip_longest(*([iter(images)] * setup[columns]["images_per_page"]))):
        result.extend([
            r"\newpage" if newpage or page_no > 0 else "",
            setup[columns]["tex_begin"],
            *[n_maps(images_on_page[no:no + columns]) for no in range(0, len(images_on_page), columns)],
            setup[columns]["tex_end"],
            ])
    return result

# ----------------------------------------------------------------------

def _blank_page() -> list[str]:
    # http://tex.stackexchange.com/questions/36880/insert-a-blank-page-after-current-page
    return [r"\newcommand\blankpage{ \newpage \vspace*{100pt} \thispagestyle{empty} \newpage }"]

def _remove_section_numbering() -> list[str]:
    # http://www.ehow.com/how_8085363_hide-section-numbers-latex.html
    return [r"\setcounter{secnumdepth}{-1}"]

def _table_of_contents() -> list[str]:
    # http://tex.stackexchange.com/questions/163986/format-table-of-contents-with-latex
    return [
        r"\titlecontents{section}[0cm]{\bfseries}{\\}{\\}{}",
        r"\titlecontents{subsection}[1em]{}{}{}{\titlerule*[5pc]{}\vspace{0.8ex}\thecontentspage}",
        r"\contentsmargin{120pt}",
        r"\cftsetindents{section}{0.5in}{0.5in}",  # http://tex.stackexchange.com/questions/50471/question-about-indent-lengths-in-toc
    ]

def _prepare_geographic_coloring(source: list[dict[str, str]]) -> list[str]:
    def color_to_latex(color: str) -> str:
        if color and color[0] == "#":
            return color[1:]
        elif color == "transparent":
            return "FFFFFF"
        else:
            return color
    color_def = [fr"\definecolor{{{en['label']}}}{{HTML}}{{{color_to_latex(en['fill'])}}}" for en in source if en.get("label")]
    rows = [fr"\cbox[{en['label']}] & {en['label']} \\" for en in source if en.get("label")]
    return [
        *color_def,
        r"\begin{tabular}{l l}",
        *rows,
        r"\end{tabular}",
    ]

# ----------------------------------------------------------------------

sSubtypeForStat = {"h1": "A(H1N1)", "h3": "A(H3N2)", "b": "B", "bvic": "BVICTORIA", "byam": "BYAMAGATA"}

sContinents = ['ASIA', 'AUSTRALIA-OCEANIA', 'NORTH-AMERICA', 'EUROPE', 'RUSSIA', 'AFRICA', 'MIDDLE-EAST', 'SOUTH-AMERICA', 'CENTRAL-AMERICA', 'all', 'sera', 'sera_unique']

sHeader = {'ASIA': 'Asia', 'AUSTRALIA-OCEANIA': 'Oceania', 'NORTH-AMERICA': 'N Amer', 'EUROPE': 'Europe', 'RUSSIA': 'Russia', 'AFRICA': 'Africa',
           'MIDDLE-EAST': 'M East', 'SOUTH-AMERICA': 'S Amer', 'CENTRAL-AMERICA': 'C Amer', 'all': 'TOTAL', 'month': 'Year-Mo', 'year': 'Year',
           'sera': 'Sera', 'sera_unique': 'Sr Uniq'}

sReYearMonth = {'month': re.compile(r'^\d{6}$', re.I), 'year': re.compile(r'^\d{4}$', re.I)}

def _statistics_table(subtype: str, lab: str, time_series: TimeSeriesRange, current_stat: Path, previous_stat: Path | None) -> list[str]:

    data = json.load(lzma.LZMAFile(current_stat, "rb"))
    data_antigens = data['antigens'][sSubtypeForStat[subtype]].get(lab_title(lab), {})
    data_sera_unique = data['sera_unique'].get(sSubtypeForStat[subtype], {})
    data_sera = data['sera'].get(sSubtypeForStat[subtype], {})
    if previous_stat and previous_stat.exists():
        previous_data = json.load(lzma.LZMAFile(previous_stat, "rb"))
        previous_data_antigens = previous_data['antigens'][sSubtypeForStat[subtype]].get(lab_title(lab), {})
        previous_data_sera_unique = previous_data['sera_unique'].get(sSubtypeForStat[subtype], {})
        previous_data_sera = previous_data['sera'].get(sSubtypeForStat[subtype], {})
    else:
        previous_data_antigens, previous_data_sera_unique, previous_data_sera = {}, {}, {}
    previous_sum: dict[str, int] = collections.defaultdict(int)

    heading = ' & '.join('\\ContinentHeading{{{}}}'.format(n) for n in (sHeader[nn] for nn in sContinents))
    heading = heading.replace('{TOTAL}', 'Total{TOTAL}').replace('{Sr Unique}', 'Last{Sr Unique}').replace('{Sr Uniq}', 'Last{Sr Uniq}')
    result = [
        r"\begin{WhoccStatisticsTable}  \hline",
        r"\PeriodHeading{Month} & " + heading + r"\\",
        r"\hline",
    ]
    for date in time_series.range_begin():
        stat_date = date.strftime("%Y%m")
        result.append(_statistics_table_make_line(stat_date, data_antigens=data_antigens.get(stat_date, {}), data_sera=data_sera.get(stat_date, {}), data_sera_unique=data_sera_unique.get(stat_date, {}), previous_data_antigens=previous_data_antigens.get(stat_date, {}), previous_data_sera=previous_data_sera.get(stat_date, {}).get('all', 0), previous_data_sera_unique=previous_data_sera_unique.get(stat_date, {}).get('all', 0)))
        if previous_data_antigens:
            for continent in sContinents[:-2]:
                previous_sum[continent] += previous_data_antigens.get(stat_date, {}).get(continent, 0)
            previous_sum['sera'] += previous_data_sera.get(stat_date, {}).get('all', 0)
            previous_sum['sera_unique'] += previous_data_sera_unique.get(stat_date, {}).get('all', 0)
    result.extend([
        r"\hline",
        _statistics_table_make_line("all", data_antigens=data_antigens.get('all', {}), data_sera=data_sera.get('all', {}), data_sera_unique=data_sera_unique.get('all', {}), previous_data_antigens=previous_sum, previous_data_sera=previous_sum.get('sera'), previous_data_sera_unique=previous_sum.get('sera_unique')),
        r"\hline",
        r"\end{WhoccStatisticsTable}",
    ])
    return result

def _statistics_table_make_line(date: str, data_antigens: dict, data_sera: dict, data_sera_unique: dict, previous_data_antigens: dict, previous_data_sera: int | None, previous_data_sera_unique: int | None) -> str:

    def diff_current_previous(continent):
        diff = data_antigens.get(continent, 0) - previous_data_antigens.get(continent, 0)
        if diff < 0:
            print(f"> {date} {continent}: Current: {data_antigens.get(continent, 0)} Previous: {previous_data_antigens.get(continent, 0)}", file=sys.stderr)
            diff = 0
        return diff

    def format_date():
        if date[0] == '9':
            result = 'Unknown'
        elif date == 'all':
            result = '\\color{WhoccStatisticsTableTotal} TOTAL'
        elif len(date) == 4 or date[4:] == '99':
            if time_series.period == 'month':
                result = '{}-??'.format(date[:4])
            else:
                result = '{}'.format(date[:4])
        else:
            result = '{}-{}'.format(date[:4], date[4:])
        return result

    data = [format_date()]
    if date == 'all':
        total = "Total"
    else:
        total = ""
    if previous_data_antigens:
        data.extend([r'\WhoccStatisticsTableCellTwo{}{{{}}}{{{}}}'.format(total, data_antigens.get(continent, 0), diff_current_previous(continent)) for continent in sContinents[:-3]])
        data.append( r'\WhoccStatisticsTableCellTwoTotal{{{}}}{{{}}}'.format(data_antigens.get('all', 0), diff_current_previous('all')))
        data.append( r'\WhoccStatisticsTableCellTwo{}{{{}}}{{{}}}'.format(total, data_sera.get('all', 0), data_sera.get('all', 0) - previous_data_sera))
        data.append( r'\WhoccStatisticsTableCellTwo{}{{{}}}{{{}}}'.format(total, data_sera_unique.get('all', 0), data_sera_unique.get('all', 0) - previous_data_sera_unique))
    else:
        data.extend([r'\WhoccStatisticsTableCellOne{}{{{}}}'.format(total, data_antigens.get(continent, 0)) for continent in sContinents[:-3]])
        data.append(r'\WhoccStatisticsTableCellOneTotal{{{}}}'.format(data_antigens.get(sContinents[-3], 0)))
        data.append( r'\WhoccStatisticsTableCellOne{}{{{}}}'.format(total, data_sera.get('all', 0)))
        data.append( r'\WhoccStatisticsTableCellOne{}{{{}}}'.format(total, data_sera_unique.get('all', 0)))
    return '  ' + ' & '.join(data) + ' \\\\'

def whole_page_image(images: list[Path]|Path, fit: bool = False) -> list[str]:
    if isinstance(images, list):
        if all(fn.exists() for fn in images):
            fns = ",".join(str(fn.resolve()) for fn in images)
            return [f"\\WholePagePdfMerge{{{fns}}}"]
        else:
            return list(itertools.chain.from_iterable(whole_page_image(fn, fit=fit) for fn in images))
    elif images.exists():
        if fit:
            return [f"\\WholePagePdfFit{{{images.resolve()}}}"]
        else:
            return [f"\\WholePagePdf{{{images.resolve()}}}"]
    else:
        return [f"\\newpage \\vspace*{{15em}} {{\\fontsize{{40}}{{50}} \\selectfont \\noindent \\rotatebox{{315}}{{ \\textbf{{ \\textcolor{{red}}{{{images}}} }} }}}}"]

# ----------------------------------------------------------------------

def _whocc_statistics_table() -> list[str]:
    return [
            r"\newcommand{\WhoccStatisticsTableCellOne}[1]{#1 & & & &}",
            r"\newcommand{\WhoccStatisticsTableCellOneTotal}[1]{\color{WhoccStatisticsTableTotal}#1 & & & & }",
            r"\newcommand{\WhoccStatisticsTableCellTwo}[2]{#1 & ( & #2 & ) &}",
            r"\newcommand{\WhoccStatisticsTableCellTwoTotal}[2]{\color{WhoccStatisticsTableTotal}#1 & \color{WhoccStatisticsTableTotal}( & \color{WhoccStatisticsTableTotal}#2 & \color{WhoccStatisticsTableTotal}) & }",
            r"\newenvironment{WhoccStatisticsTable}{",
            r"  \setlength{\tabcolsep}{0pt}",
            r"  \definecolor{AlternativeRow}{HTML}{F0F0F0}",
            r"  \rowcolors{2}{AlternativeRow}{}",
            r"  \renewcommand{\arraystretch}{1.5}",
            r"  \newcommand{\ContinentHeading}[1]{\multicolumn{5}{>{\hspace{0.3em}}c<{\hspace{0.3em}}}{##1}}",
            r"  \newcommand{\ContinentHeadingTotal}[1]{\multicolumn{5}{>{\hspace{0.3em}}c<{\hspace{0.3em}}}{\color{WhoccStatisticsTableTotal}##1}}",
            r"  \newcommand{\ContinentHeadingLast}[1]{\multicolumn{5}{>{\hspace{0.3em}}c<{\hspace{0.3em}}|}{##1}}",
            r"  \newcommand{\PeriodHeading}[1]{\multicolumn{1}{|c}{##1}}",
            r"  \scriptsize",
            r"  \begin{center}",
            r"    \begin{tabular}{|>{\hspace{0.3em}}l<{\hspace{0.3em}} *{12}{>{\hspace{0.6em}}r >{\hspace{0.3em}}lrl r<{\hspace{0.5em}}}|} % >{\hspace{0.3em}\bfseries}r >{\hspace{0.3em}}lrl r<{\hspace{0.3em}} *{2}{>{\hspace{0.3em}}r >{\hspace{0.3em}}lrl r<{\hspace{0.3em}}}}",
            r"}{\end{tabular}\end{center}\par}",
            r"\definecolor{WhoccStatisticsTableTotal}{HTML}{008000}",
    ]

def _cbox() -> list[str]:
    return [r"\newcommand\cbox[1][black]{\tikz[baseline=-0.5ex]\draw[black,fill=#1,radius=0.3em] (0,0) circle ;}"]

def _geographic_map_table() -> list[str]:
    return [
            r"\def \GeographicMapsTableMapSize {\textheight * 18 / 30} % size of an embedded geographic map",
            r"\newenvironment{GeographicMapsTable}{",
            r"  \renewcommand{\arraystretch}{2.5}",
            r"  \newcommand{\GeographicMap}[1]{\includegraphics[width=\GeographicMapsTableMapSize,frame]{##1}}",
            r"  \begin{center}",
            r"    \begin{tabular}{c}",
            r"}{\end{tabular}\end{center}\par}",
    ]

def _whole_page_pdf() -> list[str]:
    return [
            r"\newenvironment{WholePagePdfEnv}{",
            r"   \noindent",
            r"   \begin{center}",
            r"}{\end{center}\par}",
            r"% \newcommand{\WholePagePdf}[1]{\begin{WholePagePdfEnv}\pagestyle{empty} \includepdf[pages=-,pagecommand={\thispagestyle{fancy}}]{#1}\end{WholePagePdfEnv}}",
            r"\newcommand{\WholePagePdf}[1]{\begin{WholePagePdfEnv}\pagestyle{empty} \includepdf[pages={1},noautoscale=false]{#1}\end{WholePagePdfEnv}}",
            r"\newcommand{\WholePagePdfMerge}[1]{\begin{WholePagePdfEnv}\pagestyle{empty} \includepdfmerge[]{#1}\end{WholePagePdfEnv}}",
            r"\newcommand{\WholePagePdfFit}[1]{\begin{WholePagePdfEnv}\includegraphics[page=1,scale=0.9]{#1}\end{WholePagePdfEnv}}",
            r"\newcommand{\WholePagePdfTwoToc}[3]{",
            r"  \begin{WholePagePdfEnv}",
            r"    \includepdf[pages=-,pagecommand={\pagestyle{fancy}}]{#1}",
            r"    \addcontentsline{toc}{subsection}{#2}",
            r"    \includepdf[pages=-,pagecommand={\pagestyle{fancy}}]{#3}",
            r"  \end{WholePagePdfEnv}}",
    ]

def _color_coded_by_region() -> list[str]:
    return [
            r"\newcommand{\ColorCodedByRegion}{%",
            r"  \begin{tabular}{l l}",
            r"    \cbox[NorthAmerica]     & North America            \\",
            r"    \cbox[SouthAmerica]     & South America            \\",
            r"    \cbox[Europe]           & Europe                   \\",
            r"    \cbox[Africa]           & Africa                   \\",
            r"    \cbox[MiddleEast]       & MiddleEast               \\",
            r"    \cbox[Russia]           & Russia                   \\",
            r"    \cbox[Asia]             & East and South East Asia \\",
            r"    \cbox[AustraliaOceania] & Australia and Oceania    \\",
            r"    \cbox[Unknown]          & unknown                  \\",
            r"  \end{tabular}",
            r"}",
        r"\definecolor{NorthAmerica}{HTML}{000080}",
        r"\definecolor{Europe}{HTML}{00FF00}",
        r"\definecolor{MiddleEast}{HTML}{8000FF}",
        r"\definecolor{NorthAmerica}{HTML}{00008B}",
        r"\definecolor{SouthAmerica}{HTML}{40E0D0}",
        r"\definecolor{CentralAmerica}{HTML}{AAF9FF}",
        r"\definecolor{Africa}{HTML}{FF8000}",
        r"\definecolor{Asia}{HTML}{FF0000}",
        r"\definecolor{Russia}{HTML}{B03060}",
        r"\definecolor{AustraliaOceania}{HTML}{FF69B4}",
        r"\definecolor{Antarctica}{HTML}{808080}",
        r"\definecolor{ChinaSouth}{HTML}{FF0000}",
        r"\definecolor{ChinaNorth}{HTML}{6495ED}",
        r"\definecolor{ChinaUnknown}{HTML}{808080}",
        r"\definecolor{Unknown}{HTML}{808080}",
    ]

def _antigenic_map_table() -> list[str]:
    return [
            r"\def \AntigenicMapTableMapSize {(\textheight-20pt) * 9 / 30} % size of an embedded antigenic map",
            r"\def \AntigenicMapTableMapSmallSize {(\textheight-20pt) * 17 / 60} % size of an embedded antigenic map",

            r"\newenvironment{AntigenicMapTable}{",
            r"  \setlength{\tabcolsep}{7pt}",
            r"  \renewcommand{\arraystretch}{3.5}",
            r"  \newcommand{\AntigenicMap}[1]{\includegraphics[width=\AntigenicMapTableMapSize,frame]{##1}}",
            r"  \newcommand{\AntigenicMapSmall}[1]{\includegraphics[width=\AntigenicMapTableMapSmallSize,frame]{##1}}",
            r"  \begin{center}",
            r"    \begin{tabular}{c c}",
            r"}{\end{tabular}\end{center}\par}",

            r"\newenvironment{AntigenicMapTableWithSep}[3]{",
            r"  \setlength{\tabcolsep}{#1}",
            r"  \renewcommand{\arraystretch}{#2}",
            r"  \newcommand{\AntigenicMap}[1]{\includegraphics[width={(\textheight-20pt) * {#3}},frame]{##1}}",
            r"  \begin{center}",
            r"    \begin{tabular}{c c}",
            r"}{\end{tabular}\end{center}\par}",

            r"\newenvironment{AntigenicMapTable3WithSep}[3]{",
            r"  \setlength{\tabcolsep}{#1}",
            r"  \renewcommand{\arraystretch}{#2}",
            r"  \newcommand{\AntigenicMap}[1]{\includegraphics[width={(\textheight-20pt) * {#3}},frame]{##1}}",
            r"  \begin{center}",
            r"    \begin{tabular}{c c c}",
            r"}{\end{tabular}\end{center}\par}",
            ]

# ----------------------------------------------------------------------

def _phylogenetic_tree_description() -> list[str]:
    return [
        r"\noindent The phylogenetic tree is color coded by region, legend is in the bottom left corner of the next page.",
        r"\vspace{1em}",
        r"""\noindent The month in which recent strains in the tree were isolated is indicated
        by horizontal bars to the right of the tree drawn at the same vertical
        position as the position of the strain in the tree. The horizontal bars
        are also colored by region. This tree is zoomable.""",
        r"\vspace{1em}",
        r"""\noindent Nucleotide sequences of the HA1 domain of the HA were aligned. The 
        phylogenetic tree was constructed using CMAPLE v1.0.0 under the GTR substitution model, 
        and zero-length branches were collapsed into multifurcations.""",
    ]

def _phylogenetic_tree_2_description() -> list[str]:
    return [
        r"\noindent The tree uses a subset of the data to highlight recent circulation (less sequence data due to COVID-19).",
    ]

# ======================================================================

def _now() -> str:
    LOCAL_TIMEZONE = datetime.datetime.now(datetime.timezone.utc).astimezone().tzinfo # https://stackoverflow.com/questions/2720319/python-figure-out-local-timezone
    return datetime.datetime.now(LOCAL_TIMEZONE).strftime("%Y-%m-%d %H:%M %Z")

# ======================================================================
